name: Bug Report

description: Something isn’t working as expected and needs to be fixed.

title: "[Bug]: *Briefly describe the issue*"

labels:
  - Bug

body:
  - type: input
    attributes:
      label: What went wrong?
      description: Clearly describe the unexpected behavior you encountered in the game.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version?
      description: Specify the Old Prodigy version where this bug occurred.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce this issue?
      description: Provide step-by-step instructions to trigger this bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Console Logs (Press F12 or CTRL+SHIFT+J)
      description: Share any relevant console logs from the developer tools. Even if no errors appear, list what was logged during the bug occurrence.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I confirm that this bug report is for a bug occurring on "healingmunch.github.io/XPMUser.github.io" and NOT on other websites.
          required: true
        - label: This report is about a problem with an existing feature, not a feature request.
          required: true
        - label: I confirm this is a genuine issue with an existing feature.
          required: true
        - label: I understand this issue should not be marked as completed unless the bug is fully fixed.
          required: true
        - label: I agree not to misuse bug reports to intentionally disrupt the game as a collaborator.
          required: true
        - label: I agree to be patient when you need some time to fix this bug or other bugs.
          required: true
